apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 307546041091.dkr.ecr.ap-south-1.amazonaws.com/my-app:${{ github.sha }}
        ports:
        - containerPort: 3000
