name: Build, Tag, and Push to ECR

on:
    workflow_dispatch:
      inputs:
        title:
          description: 'Title for the release'
          required: false
        # version:
        #   description: 'Version to release'
        #   required: true
        description:
          description: 'Description for the release'
          required: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 430118812416.dkr.ecr.us-west-2.amazonaws.com

      - name: Build the Docker image
        run: |
          docker build -t my-app:latest .

      - name: Tag the Docker image with Git SHA
        run: |
          export TAG=${{ github.sha }}
          docker tag my-app:latest 430118812416.dkr.ecr.us-west-2.amazonaws.com/my-app:${TAG}

      - name: Push the Docker image to Amazon ECR
        run: |
          docker push 430118812416.dkr.ecr.us-west-2.amazonaws.com/my-app:${{ github.sha }}

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name my-eks-cluster
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
